name: SuperBuild

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  fmt:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install dependencies
        uses: lukka/get-cmake@latest
        with:
          cmakeVersion: "~3.20.0"
          ninjaVersion: latest

      - name: Configure
        run: cmake -B /home/runner/build -S . -DCMAKE_BUILD_TYPE=Release -G Ninja

      - name: Build fmt
        run: cmake --build /home/runner/build -t fmt

      - name: Upload fmt install tree
        uses: actions/upload-artifact@v3
        with:
          name: fmt-install
          path: /home/runner/build/install/fmt
          retention-days: 1

  spdlog:
    runs-on: ubuntu-latest
    needs: fmt

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install dependencies
        uses: lukka/get-cmake@latest
        with:
          cmakeVersion: "~3.20.0"
          ninjaVersion: latest

      - name: Configure
        run: cmake -B /home/runner/build -S . -DCMAKE_BUILD_TYPE=Release -G Ninja

      - name: Download fmt install tree
        uses: actions/download-artifact@v3
        with:
          name: fmt-install
          path: /home/runner/build/install/fmt

      - name: Build spdlog
        run: cmake --build /home/runner/build -t spdlog -- -d explain

      - name: Upload spdlog install tree
        uses: actions/upload-artifact@v3
        with:
          name: spdlog-install
          path: /home/runner/build/install/spdlog
          retention-days: 1
